-- ============================================================================
-- Phase 1 image seed — applied 2026-05-13 to acxsxjmqgvkceqahwkpz.
--
-- Idempotent. Re-run via:
--   psql "$DATABASE_URL" -f supabase/seed/01_phase1_image_seed.sql
--   (or paste into Supabase Studio → SQL editor)
--
-- Prerequisite: the 4 frame PNGs and their preview JPGs must already exist in
-- the `photos` Supabase Storage bucket. They are generated by
-- `scripts/generate-frame-assets.mjs` and uploaded via
-- `scripts/upload-frame-assets.sh`. Both scripts are checked in.
--
-- What this seed does:
--   1. Refreshes the existing single product_images row (thumbnail) and the
--      first gallery row to point at curated Unsplash editorial photography.
--   2. Adds 3 more gallery images + 2 guide images for richer detail pages.
--   3. Updates the single seeded frame_asset (black) to the normalized
--      inner_rect = { x:0.08, y:0.08, w:0.84, h:0.84 } that matches the
--      generated PNG geometry.
--   4. Adds 3 more frame_asset colorways (brown / white / natural).
--   5. Expands product_variants from 4 (black × 4 sizes) to 16
--      (4 colors × 4 sizes).
-- ============================================================================

-- Convenience locals
DO $$
DECLARE
  product_id uuid := '00000000-0000-0000-0000-000000000010';
  inner_rect jsonb := '{"x":0.08,"y":0.08,"w":0.84,"h":0.84}'::jsonb;
  url_prefix text := 'https://acxsxjmqgvkceqahwkpz.supabase.co/storage/v1/object/public/photos/';
BEGIN
  ------------------------------------------------------------------
  -- 1. product_images — refresh thumb + first gallery
  ------------------------------------------------------------------
  UPDATE product_images
     SET image_url = 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=1200&q=85&auto=format&fit=crop',
         alt_text  = '베이직 액자 — 거실 갤러리 컨셉'
   WHERE id = '00000000-0000-0000-0000-000000000201';

  UPDATE product_images
     SET image_url = 'https://images.unsplash.com/photo-1582738411706-bfc8e691d1c2?w=1600&q=85&auto=format&fit=crop',
         alt_text  = '베이직 액자 — 명화 컬렉션 디스플레이'
   WHERE id = '00000000-0000-0000-0000-000000000202';

  ------------------------------------------------------------------
  -- 2. product_images — additional gallery + guide rows
  ------------------------------------------------------------------
  INSERT INTO product_images (product_id, image_url, alt_text, type, sort_order)
  VALUES
    (product_id, 'https://images.unsplash.com/photo-1565195972571-edec74b0bef8?w=1600&q=85&auto=format&fit=crop',
       '우드 프레임 — 자연광', 'gallery', 1),
    (product_id, 'https://images.unsplash.com/photo-1597423498219-04418210827d?w=1600&q=85&auto=format&fit=crop',
       '갤러리 월 — 사이즈 혼합 배치', 'gallery', 2),
    (product_id, 'https://images.unsplash.com/photo-1556015048-4d3aa10df74c?w=1600&q=85&auto=format&fit=crop',
       '화이트 매트 — 사진 디테일', 'gallery', 3),
    (product_id, 'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=1600&q=85&auto=format&fit=crop',
       '제작 과정 — 작업실', 'guide', 0),
    (product_id, 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=1600&q=85&auto=format&fit=crop',
       '포장 및 배송', 'guide', 1)
  ON CONFLICT DO NOTHING;

  ------------------------------------------------------------------
  -- 3. frame_assets — black inner_rect normalization
  ------------------------------------------------------------------
  UPDATE frame_assets
     SET inner_rect = inner_rect
   WHERE id = '00000000-0000-0000-0000-000000000301';

  ------------------------------------------------------------------
  -- 4. frame_assets — brown / white / natural
  ------------------------------------------------------------------
  INSERT INTO frame_assets (product_id, color_code, color_label, png_url, preview_url, inner_rect)
  VALUES
    (product_id, 'brown',   '월넛 우드',
       url_prefix || 'frame-brown.png',
       url_prefix || 'frame-brown-preview.jpg', inner_rect),
    (product_id, 'white',   '화이트',
       url_prefix || 'frame-white.png',
       url_prefix || 'frame-white-preview.jpg', inner_rect),
    (product_id, 'natural', '내추럴 오크',
       url_prefix || 'frame-natural.png',
       url_prefix || 'frame-natural-preview.jpg', inner_rect)
  ON CONFLICT (product_id, color_code) DO UPDATE
    SET png_url     = EXCLUDED.png_url,
        preview_url = EXCLUDED.preview_url,
        inner_rect  = EXCLUDED.inner_rect;

  ------------------------------------------------------------------
  -- 5. product_variants — 3 new colorways × 4 sizes (12 rows)
  ------------------------------------------------------------------
  INSERT INTO product_variants
    (product_id, size_code, size_label, width_mm, height_mm,
     color_code, matte_code, paper_code, price, stock, is_active)
  VALUES
    (product_id, '4x6',   '4×6 (10×15cm)', 102, 152, 'brown',   'none', 'glossy',  5800, 99999, true),
    (product_id, '5x7',   '5×7 (13×18cm)', 127, 178, 'brown',   'none', 'glossy',  8800, 99999, true),
    (product_id, '8x10',  '8×10 (20×25cm)', 203, 254, 'brown',  'none', 'glossy', 15800, 99999, true),
    (product_id, '11x14', '11×14 (28×36cm)', 279, 356, 'brown', 'none', 'glossy', 26800, 99999, true),

    (product_id, '4x6',   '4×6 (10×15cm)', 102, 152, 'white',   'none', 'glossy',  4800, 99999, true),
    (product_id, '5x7',   '5×7 (13×18cm)', 127, 178, 'white',   'none', 'glossy',  7800, 99999, true),
    (product_id, '8x10',  '8×10 (20×25cm)', 203, 254, 'white',  'none', 'glossy', 14800, 99999, true),
    (product_id, '11x14', '11×14 (28×36cm)', 279, 356, 'white', 'none', 'glossy', 24800, 99999, true),

    (product_id, '4x6',   '4×6 (10×15cm)', 102, 152, 'natural', 'none', 'glossy',  5800, 99999, true),
    (product_id, '5x7',   '5×7 (13×18cm)', 127, 178, 'natural', 'none', 'glossy',  8800, 99999, true),
    (product_id, '8x10',  '8×10 (20×25cm)', 203, 254, 'natural','none', 'glossy', 15800, 99999, true),
    (product_id, '11x14', '11×14 (28×36cm)', 279, 356, 'natural','none', 'glossy', 26800, 99999, true)
  ON CONFLICT (product_id, size_code, color_code, matte_code, paper_code) DO NOTHING;

  ------------------------------------------------------------------
  -- 6. Admin user — managed via the Auth admin API, not this seed.
  -- See scripts/seed-admin-user.sh for the curl invocations.
  ------------------------------------------------------------------
END $$;
