-- 017_previews_bucket_private.sql
-- P1-01: Make the `previews` bucket private and add an ADR-020 note.
--
-- Before this migration:
--   - `previews` was public — any URL was world-readable indefinitely.
--   - 300dpi print files (user photo composited onto frame) were exposed
--     to anyone who guessed or obtained the URL.
--
-- After:
--   - Bucket is private; direct object URLs return 403.
--   - Access requires a signed URL generated by the service role.
--   - `renderOrderItemPrint` in pipeline.ts now calls `createSignedUrl`
--     (7-day TTL) and stores the result in order_items.print_file_url.
--   - After 7 days the URL expires; re-triggering the render regenerates it.
--
-- ADR-020 (implicit): Phase 1 trade-off — 7-day signed URLs are stored
-- in the DB. Phase 2 will add an admin-side URL-refresh endpoint and
-- optionally move to a presigned CDN distribution.

-- Make the bucket private (non-public).
UPDATE storage.buckets
  SET public = false
  WHERE name = 'previews'
    AND public = true;

-- RLS: service role can read/write (already bypasses RLS).
-- Authenticated admin users can read objects in the previews bucket.
-- Anonymous and regular authenticated users cannot access it at all.

-- Drop any existing permissive read policy first (idempotent).
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'storage'
      AND tablename = 'objects'
      AND policyname = 'previews_public_read'
  ) THEN
    DROP POLICY previews_public_read ON storage.objects;
  END IF;
END $$;

-- Admin-only read: app_metadata.role = 'admin' via JWT.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'storage'
      AND tablename = 'objects'
      AND policyname = 'previews_admin_read'
  ) THEN
    CREATE POLICY previews_admin_read ON storage.objects
      FOR SELECT
      TO authenticated
      USING (
        bucket_id = 'previews'
        AND (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
      );
  END IF;
END $$;
